package com.web.demo.mapper;

import com.web.demo.model.Catalog;
import com.web.demo.model.CatalogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    long countByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int deleteByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int insert(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int insertSelective(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    List<Catalog> selectByExample(CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    Catalog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int updateByExampleSelective(@Param("record") Catalog record, @Param("example") CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int updateByExample(@Param("record") Catalog record, @Param("example") CatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int updateByPrimaryKeySelective(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int updateByPrimaryKey(Catalog record);
}