package com.web.demo.mapper;

import com.web.demo.model.CustomerType;
import com.web.demo.model.CustomerTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    long countByExample(CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int deleteByExample(CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int insert(CustomerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int insertSelective(CustomerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    List<CustomerType> selectByExample(CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    CustomerType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int updateByExampleSelective(@Param("record") CustomerType record, @Param("example") CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int updateByExample(@Param("record") CustomerType record, @Param("example") CustomerTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int updateByPrimaryKeySelective(CustomerType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    int updateByPrimaryKey(CustomerType record);
}