package com.web.demo.model;

import java.util.Date;

public class AccountType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer insertUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Date insertDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_type.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Boolean isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.id
     *
     * @return the value of account_type.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.id
     *
     * @param id the value for account_type.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.type
     *
     * @return the value of account_type.type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.type
     *
     * @param type the value for account_type.type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.insert_user
     *
     * @return the value of account_type.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.insert_user
     *
     * @param insertUser the value for account_type.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setInsertUser(Integer insertUser) {
        this.insertUser = insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.insert_date
     *
     * @return the value of account_type.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.insert_date
     *
     * @param insertDate the value for account_type.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.modify_user
     *
     * @return the value of account_type.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.modify_user
     *
     * @param modifyUser the value for account_type.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.modify_date
     *
     * @return the value of account_type.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.modify_date
     *
     * @param modifyDate the value for account_type.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_type.is_enable
     *
     * @return the value of account_type.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_type.is_enable
     *
     * @param isEnable the value for account_type.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }
}