package com.web.demo.model;

import java.util.Date;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.username
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer insertUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Date insertDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Boolean isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.rights
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Object rights;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.username
     *
     * @return the value of account.username
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.username
     *
     * @param username the value for account.username
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.type
     *
     * @return the value of account.type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.type
     *
     * @param type the value for account.type
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.insert_user
     *
     * @return the value of account.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.insert_user
     *
     * @param insertUser the value for account.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setInsertUser(Integer insertUser) {
        this.insertUser = insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.insert_date
     *
     * @return the value of account.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.insert_date
     *
     * @param insertDate the value for account.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.modify_user
     *
     * @return the value of account.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.modify_user
     *
     * @param modifyUser the value for account.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.modify_date
     *
     * @return the value of account.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.modify_date
     *
     * @param modifyDate the value for account.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.is_enable
     *
     * @return the value of account.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.is_enable
     *
     * @param isEnable the value for account.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.rights
     *
     * @return the value of account.rights
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Object getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.rights
     *
     * @param rights the value for account.rights
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setRights(Object rights) {
        this.rights = rights;
    }
}