package com.web.demo.model;

import java.util.Date;

public class Catalog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.catalog_name
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private String catalogName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer insertUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Date insertDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Boolean isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.parent_id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.id
     *
     * @return the value of catalog.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.id
     *
     * @param id the value for catalog.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.catalog_name
     *
     * @return the value of catalog.catalog_name
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.catalog_name
     *
     * @param catalogName the value for catalog.catalog_name
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.insert_user
     *
     * @return the value of catalog.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.insert_user
     *
     * @param insertUser the value for catalog.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setInsertUser(Integer insertUser) {
        this.insertUser = insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.insert_date
     *
     * @return the value of catalog.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.insert_date
     *
     * @param insertDate the value for catalog.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.modify_user
     *
     * @return the value of catalog.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.modify_user
     *
     * @param modifyUser the value for catalog.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.modify_date
     *
     * @return the value of catalog.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.modify_date
     *
     * @param modifyDate the value for catalog.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.is_enable
     *
     * @return the value of catalog.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.is_enable
     *
     * @param isEnable the value for catalog.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.parent_id
     *
     * @return the value of catalog.parent_id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.parent_id
     *
     * @param parentId the value for catalog.parent_id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}