package com.web.demo.model;

import java.util.Date;

public class Customer {
	public Customer()
	{
		this.address = null;
		this.birthDay = null;
		this.email = null;
		this.firstName = null;
		this.idCard = null;
		this.insertDate = null;
		this.isEnable =false;
		this.lastName =null;
		this.loginName = null;
		this.modifyDate = null;
		this.password = null;
		this.phoneNumber = null;
		this.type = 1;
		
	}
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.login_name
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.password
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.email
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone_number
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private Integer phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.birth_day
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private Date birthDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.first_name
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.last_name
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id_card
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private Integer idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.insert_date
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private Date insertDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.is_enable
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private Boolean isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.type
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.modify_date
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.login_name
     *
     * @return the value of customer.login_name
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.login_name
     *
     * @param loginName the value for customer.login_name
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.password
     *
     * @return the value of customer.password
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.password
     *
     * @param password the value for customer.password
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.email
     *
     * @return the value of customer.email
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.email
     *
     * @param email the value for customer.email
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone_number
     *
     * @return the value of customer.phone_number
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public Integer getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone_number
     *
     * @param phoneNumber the value for customer.phone_number
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setPhoneNumber(Integer phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address
     *
     * @return the value of customer.address
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address
     *
     * @param address the value for customer.address
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.birth_day
     *
     * @return the value of customer.birth_day
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.birth_day
     *
     * @param birthDay the value for customer.birth_day
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.first_name
     *
     * @return the value of customer.first_name
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.first_name
     *
     * @param firstName the value for customer.first_name
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.last_name
     *
     * @return the value of customer.last_name
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.last_name
     *
     * @param lastName the value for customer.last_name
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id_card
     *
     * @return the value of customer.id_card
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public Integer getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id_card
     *
     * @param idCard the value for customer.id_card
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setIdCard(Integer idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.insert_date
     *
     * @return the value of customer.insert_date
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.insert_date
     *
     * @param insertDate the value for customer.insert_date
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.is_enable
     *
     * @return the value of customer.is_enable
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.is_enable
     *
     * @param isEnable the value for customer.is_enable
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.type
     *
     * @return the value of customer.type
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.type
     *
     * @param type the value for customer.type
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.modify_date
     *
     * @return the value of customer.modify_date
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.modify_date
     *
     * @param modifyDate the value for customer.modify_date
     *
     * @mbg.generated Fri Mar 22 14:38:28 ICT 2019
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
    
    public String getFullName() {
    	String fullName = this.firstName +" " + this.lastName;
    	return fullName;
    }
}