package com.web.demo.model;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.transaction_id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.product_id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.quantity
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.amount
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Date insertDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Boolean isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer insertUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    private Integer modifyUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.transaction_id
     *
     * @return the value of order.transaction_id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.transaction_id
     *
     * @param transactionId the value for order.transaction_id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.product_id
     *
     * @return the value of order.product_id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.product_id
     *
     * @param productId the value for order.product_id
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.quantity
     *
     * @return the value of order.quantity
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.quantity
     *
     * @param quantity the value for order.quantity
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amount
     *
     * @return the value of order.amount
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.amount
     *
     * @param amount the value for order.amount
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.insert_date
     *
     * @return the value of order.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.insert_date
     *
     * @param insertDate the value for order.insert_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.modify_date
     *
     * @return the value of order.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.modify_date
     *
     * @param modifyDate the value for order.modify_date
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.is_enable
     *
     * @return the value of order.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.is_enable
     *
     * @param isEnable the value for order.is_enable
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.insert_user
     *
     * @return the value of order.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.insert_user
     *
     * @param insertUser the value for order.insert_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setInsertUser(Integer insertUser) {
        this.insertUser = insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.modify_user
     *
     * @return the value of order.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.modify_user
     *
     * @param modifyUser the value for order.modify_user
     *
     * @mbg.generated Sat Mar 23 15:08:44 ICT 2019
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }
}